theme: jekyll-theme-cayman
title: Ayushi Rastogi's Data Science projects
description: A repo of data science and machine learning projects. A site to know more about Ayushi Rastogi and how she's doing in Data Science and Data Analytics. It includes Data Science Projects she has done so far which showcase her skills and knowledge.
